//
// Created by william on 27/08/18.
//

#ifndef CWRU_DAVINCI_SKILLS_AND_DEMO_DAVINCISKILLBASE_H
#define CWRU_DAVINCI_SKILLS_AND_DEMO_DAVINCISKILLBASE_H

class DavinciSkillBase {

};

#endif //CWRU_DAVINCI_SKILLS_AND_DEMO_DAVINCISKILLBASE_H
